FROM ubuntu:18.04

# Install essential dependencies

RUN apt-get update && apt-get install -y \
      build-essential \
      curl \
      libcurl3-dev \
      libssl-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install the TensorFlow Model Server
RUN echo "deb [arch=amd64] http://storage.googleapis.com/tensorflow-serving-apt stable tensorflow-model-server tensorflow-model-server-universal" | \
    tee /etc/apt/sources.list.d/tensorflow-serving.list && \
    curl https://storage.googleapis.com/tensorflow-serving-apt/tensorflow-serving.release.pub.gpg | apt-key add - && \
    apt-get update && \
    apt-get install tensorflow-model-server=2.1.0


# Mount the models
VOLUME /tensorflow/models

# GRPC port
EXPOSE 7000
CMD tensorflow_model_server --port=7000 --model_config_file=/tensorflow/models/config.tf
